name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: ./mvnw clean package -DskipTests
    
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: omdb-mcp-server-jar
        path: target/*.jar
        retention-days: 30
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: omdb-mcp-server:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        load: true
    
    - name: Test Docker image
      timeout-minutes: 5
      run: |
        # Test that the container starts and responds to health check
        echo "Starting Docker container test..."
        docker run -d --name test-container -p 8080:8080 omdb-mcp-server:latest
        echo "Container started, waiting for initialization..."
        sleep 15
        
        # Check if the container is running
        echo "Checking container status..."
        docker ps | grep test-container || (echo "Container not running!" && docker logs test-container && exit 1)
        
        # Check logs for any obvious errors
        echo "Container logs:"
        docker logs test-container
        
        # Clean up
        echo "Cleaning up test container..."
        docker stop test-container
        docker rm test-container
        echo "Docker test completed successfully!"

  integration-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Run integration tests
      run: ./mvnw clean test -Dtest="*IT,*IntegrationTest"
      continue-on-error: true
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: integration-test-results
        path: target/surefire-reports/
