name: Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  dependency-updates:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Check for dependency updates
      run: ./mvnw versions:display-dependency-updates
    
    - name: Check for plugin updates
      run: ./mvnw versions:display-plugin-updates
    
    - name: Update dependencies (patch versions only)
      run: |
        ./mvnw versions:use-latest-releases -DallowSnapshots=false -DallowMajorUpdates=false -DallowMinorUpdates=false
    
    - name: Test with updated dependencies
      run: ./mvnw clean test
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies (patch versions)'
        title: 'Automated dependency updates'
        body: |
          ## Automated Dependency Updates
          
          This PR contains automated updates to patch versions of dependencies.
          
          ### Changes
          - Updated dependencies to latest patch versions
          - All tests are passing
          
          ### Review Notes
          - Only patch version updates are included for safety
          - Please review the changes and merge if appropriate
        branch: automated-dependency-updates
        delete-branch: true

  security-updates:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Run OWASP Dependency Check
      run: |
        ./mvnw org.owasp:dependency-check-maven:check
    
    - name: Upload OWASP report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: owasp-dependency-check-report
        path: target/dependency-check-report.html
